### ISSUE TITLE
Another news to evaluate?

### ISSUE THREAD

**Issue by mendo1024** [crypto-asset-resources/News-Media-Ranking#1]
The Merkle - Category: Crypto
Medium - coin and crypto

**Comment by crypto-check** [comment]
> The Merkle - Category: Crypto
> Medium - coin and crypto

The Merkle is a good find! Do you have any links to articles that would reduce their ratings based on the break downs? 

I think Medium would be a bit tough, because it's more of a blogging site rather than a news site. What do you think?

**Comment by mendo1024** [comment]
You are right with the medium, that it is blog-like. But I found there very one of the best articles about crypto, though. The merkle I chosed to follow for two reasons. Not more articles than 5-10 per day even in hype time. Second reason was their selection which does not seems to be biased - just feeling - no prove. So difficult to say. Maybe would be interesting to see which coins are on which portals most often reported. That would maybe suggest some biases.
